services:
  - type: web
    name: feedback-app
    env: python
    plan: free
    pythonVersion: 3.11.9
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
    startCommand: gunicorn feedback_system.wsgi:application
